name: Node

on: [pull_request, push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup env
        uses: ./.github/workflows/common

      - run: npm run lint

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup env
        uses: ./.github/workflows/common

      - run: npm run test
